# Generated by Skyramp v1.3.36 on 2026-08-05 12:08:27.766425297 +0000 UTC m=+584.696151012
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/{slug}/scale \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipe_scale_default_factor_contract_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--path-params slug=default-factor-test-recipe \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import re
import json


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")


def _auth_headers():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


def setup_module(module):
    client = skyramp.Client()
    client.send_request(
        url=URL,
        path="/api/recipes",
        method="POST",
        body=json.dumps({"name": "Default Factor Test Recipe"}),
        headers=_auth_headers()
    )


def teardown_module(module):
    client = skyramp.Client()
    client.send_request(
        url=URL,
        path="/api/recipes/default-factor-test-recipe",
        method="DELETE",
        headers=_auth_headers()
    )


# contract test for /api/recipes/{slug}/scale GET
def test_scale_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "default-factor-test-recipe"

    # Execute Request
    scale_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/{slug}/scale",
        method="GET",
        headers=headers,
        path_params={"slug": slug}
    )

    # Generated Assertions
    assert scale_GET_response.status_code == 200
    assert skyramp.get_response_value(scale_GET_response, "slug") == "default-factor-test-recipe"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(scale_GET_response, "id"), re.IGNORECASE) is not None


if __name__ == "__main__":
    test_scale_get()
