# Generated by Skyramp v1.3.29 on 2026-06-25 20:38:49.301415628 +0000 UTC m=+326.064623444
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_stats_create_and_read_integration_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie/mealie/tests/scenario_recipe-stats-create-and-read.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "Stats Test Recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/stats-test-recipe/stats",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.get_response_value(stats_GET_response, "ingredientCount") == 1
    assert skyramp.get_response_value(stats_GET_response, "instructionCount") == 1
    assert skyramp.get_response_value(stats_GET_response, "toolCount") == 0
    assert skyramp.get_response_value(stats_GET_response, "tagCount") == 0
    assert skyramp.get_response_value(stats_GET_response, "categoryCount") == 0


if __name__ == "__main__":
    test_integration()
