# Generated by Skyramp v1.3.29 on 2026-06-25 20:38:51.230389504 +0000 UTC m=+327.993597330
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_stats_full_recipe_integration_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie/mealie/tests/scenario_recipe-stats-full-recipe.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    recipes = "full-stats-test-recipe"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "Full Stats Test Recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Request Body
    recipes_recipes_PUT_request_body = r'''{
        "name": "Full Stats Test Recipe",
        "recipeIngredient": [
            {
                "note": "flour"
            },
            {
                "note": "sugar"
            }
        ],
        "recipeInstructions": [
            {
                "text": "Mix dry ingredients"
            },
            {
                "text": "Bake at 350F"
            },
            {
                "text": "Cool before serving"
            }
        ]
    }'''
    
    # Execute Request
    recipes_recipes_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="PATCH",
        body=recipes_recipes_PUT_request_body,
        headers=headers,
        path_params={"recipes": recipes}
    )
    # Generated Assertions
    assert recipes_recipes_PUT_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_PUT_response, "name") == "Full Stats Test Recipe"
    assert skyramp.get_response_value(recipes_recipes_PUT_response, "slug") == recipes

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}/stats",
        method="GET",
        headers=headers,
        path_params={"recipes": skyramp.get_response_value(recipes_recipes_PUT_response, "slug")}
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200
    assert skyramp.get_response_value(stats_GET_response, "ingredientCount") == 2
    assert skyramp.get_response_value(stats_GET_response, "instructionCount") == 3
    assert skyramp.get_response_value(stats_GET_response, "toolCount") == 0
    assert skyramp.get_response_value(stats_GET_response, "tagCount") == 0
    assert skyramp.get_response_value(stats_GET_response, "categoryCount") == 0


if __name__ == "__main__":
    test_integration()
