# Generated by Skyramp v1.3.29 on 2026-06-25 20:38:46.883272816 +0000 UTC m=+323.646480632
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/{slug}/stats \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipe_stats_contract_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--path-params slug=nonexistent-recipe-a1b2c3d4 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes/{slug}/stats GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "nonexistent-recipe-a1b2c3d4"

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/{slug}/stats",
        method="GET",
        headers=headers,
        path_params={"slug": slug}
    )

    # Generated Assertions
    assert stats_GET_response.status_code == 404
    assert skyramp.get_response_value(stats_GET_response, "detail") is not None


if __name__ == "__main__":
    test_stats_get()
