# Generated by Skyramp v1.3.36 on 2026-08-05 12:07:17.486323174 +0000 UTC m=+514.416048879
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/any-recipe/scale \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipe_scale_auth_required_contract_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes/any-recipe/scale GET
def test_scale_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    scale_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/any-recipe/scale",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert scale_GET_response.status_code == 401
    assert skyramp.get_response_value(scale_GET_response, "detail") == "Could not validate credentials"


if __name__ == "__main__":
    test_scale_get()
