# Generated by Skyramp v1.3.29 on 2026-06-25 19:44:02.995693024 +0000 UTC m=+461.429156698
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_create_and_scale_integration_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie/mealie/tests/scenario_recipe-create-and-scale.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    recipes = "scale-test-recipe"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "Scale Test Recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201
    assert skyramp.get_response_value(recipes_POST_response, "") is not None

    # Execute Request
    scale_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}/scale",
        method="GET",
        headers=headers,
        path_params={"recipes": recipes},
        query_params={"scale": ["2"]}
    )
    # Generated Assertions
    assert scale_GET_response.status_code == 200
    assert skyramp.get_response_value(scale_GET_response, "name") == "Scale Test Recipe"
    assert skyramp.get_response_value(scale_GET_response, "slug") == recipes
    assert skyramp.get_response_value(scale_GET_response, "recipeServings") is not None
    assert skyramp.get_response_value(scale_GET_response, "id") is not None


if __name__ == "__main__":
    test_integration()
